//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RConDevServer.Protocol.Dice.Battlefield3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RConDevServer.Protocol.Dice.Battlefield3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bf3_logo {
            get {
                object obj = ResourceManager.GetObject("bf3_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words sequences contains invalid arguments or values..
        /// </summary>
        internal static string EXC_MSG_INVALID_ARGUMENT {
            get {
                return ResourceManager.GetString("EXC_MSG_INVALID_ARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence &apos;{0}&apos; has not the expected length of {1} at maximum..
        /// </summary>
        internal static string EXC_MSG_MAX_SEQUENCE_LENGTH_NOT_SET {
            get {
                return ResourceManager.GetString("EXC_MSG_MAX_SEQUENCE_LENGTH_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence &apos;{0}&apos; has not the expected length of {1} at minimum..
        /// </summary>
        internal static string EXC_MSG_MIN_SEQUENCE_LENGTH_NOT_SET {
            get {
                return ResourceManager.GetString("EXC_MSG_MIN_SEQUENCE_LENGTH_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string does not start with the expected value: {0} ..
        /// </summary>
        internal static string EXC_MSG_NOT_STARTS_WITH {
            get {
                return ResourceManager.GetString("EXC_MSG_NOT_STARTS_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence &apos;{0}&apos; does not represent a PlayerSubset instance..
        /// </summary>
        internal static string EXC_MSG_PLAYER_SUBSET_NOT_BUILT {
            get {
                return ResourceManager.GetString("EXC_MSG_PLAYER_SUBSET_NOT_BUILT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence &apos;{0}&apos; has not the expected length of {1}..
        /// </summary>
        internal static string EXC_MSG_SEQUENCE_LENGTH_NOT_SET {
            get {
                return ResourceManager.GetString("EXC_MSG_SEQUENCE_LENGTH_NOT_SET", resourceCulture);
            }
        }
    }
}
